name: moi
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  animated_theme_switcher: ^2.0.10
  animations: ^2.0.11
  bubble: ^1.1.9+1
  cached_network_image: ^3.0.0
  cloud_firestore: ^4.14.0
  connectivity: null
  contacts_service: ^0.6.3
  convex_bottom_bar: ^3.0.0
  country_code_picker: null
  country_pickers: ^2.0.0
  cupertino_icons: ^1.0.6
  date_format: ^2.0.2
  edge_alerts: ^0.0.1
  file_picker: null
  firebase_analytics: null
  firebase_auth: ^4.16.0
  firebase_auth_platform_interface: ^7.0.9
  firebase_auth_web: ^5.8.13
  firebase_core: ^2.32.0
  firebase_core_platform_interface: ^5.0.0
  firebase_dynamic_links: ^5.4.8
  firebase_messaging: ^14.7.10
  firebase_service: ^0.0.1+1
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.5
  flutter_localization: ^0.2.0
  flutter_sound: ^9.2.13
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: 0.7.0
  flutter_toggle_tab: ^1.1.2
  font_awesome_flutter: ^10.7.0
  get_it: ^7.6.7
  google_fonts: null
  google_maps_flutter: ^2.0.3
  http: ^1.2.1
  image_cropper: null
  image_picker: ^1.0.7
  intl: ^0.19.0
  localstorage: ^4.0.1+4
  location: ^5.0.3
  mask_text_input_formatter: ^2.9.0
  material_design_icons_flutter: ^7.0.7296
  modal_progress_hud_nsn: ^0.5.1
  path_provider: null
  percent_indicator: ^4.2.3
  permission_handler: null
  photo_view: ^0.14.0
  pin_code_fields: ^8.0.1
  pin_code_text_field: ^1.7.1
  provider: null
  responsive_builder: ^0.7.0
  shared_preferences: ^2.0.5
  sms_autofill: ^2.3.0
  speech_to_text: ^6.6.0
  stylishbutton: ^0.0.3+1
  timeago: ^3.0.2
  toastification: 1.0.0
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/
    - i18n/en.json
    - i18n/ar.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MoiIcons
      fonts:
        - asset: icons/MoiIcons.ttf
    - family: Hacen
      fonts:
        - asset: fonts/Hacen.ttf
    - family: Hacen_Liner
      fonts:
        - asset: fonts/Hacen_Liner_Print-out.ttf
    - family: Hacen_Liner_Light
      fonts:
        - asset: fonts/Hacen_Liner_Print-out_Light.ttf
    - family: Cairo-Black
      fonts:
        - asset: fonts/Cairo-Black.ttf
    - family: Cairo-Bold
      fonts:
        - asset: fonts/Cairo-Bold.ttf
    - family: Cairo-ExtraLight
      fonts:
        - asset: fonts/Cairo-ExtraLight.ttf
    - family: Cairo-Light
      fonts:
        - asset: fonts/Cairo-Light.ttf
    - family: Cairo-Regular
      fonts:
        - asset: fonts/Cairo-Regular.ttf
    - family: Cairo-SemiBold
      fonts:
        - asset: fonts/Cairo-SemiBold.ttf
  #  fonts:
  #     - family: MoiIcons
  #       fonts:
  #         - asset: icons/MoiIcons.ttf
  #     - family: Hacen
  #       fonts:
  #         - asset: fonts/Hacen.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
